services:
  backend:
    build: ./backend
    ports:
      - "8090:8090"
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "5174:80"
    depends_on:
      - backend
    restart: unless-stopped
